//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Lead.Detect.DatabaseHelper
{
    /// <summary>
    /// 实体类ProductDataEntity。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("ProductData")]
    [Serializable]
    public partial class ProductDataEntity : Entity
    {
        #region Model
        private string _StartTime;
        private string _FinishTime;
        private string _Status;
        private string _Error;
        private decimal? _CT;
        private string _Barcode;
        private string _ProductType;
        private string _Description;
        private string _Spcs;
        private string _Tests;
        private string _Raws;
        private string _MachineID;
        private string _ProductID;
        private string _PartID;
        private string _OpID;

        /// <summary>
        /// 
        /// </summary>
        [Field("StartTime")]
        public string StartTime
        {
            get { return _StartTime; }
            set
            {
                this.OnPropertyValueChange("StartTime");
                this._StartTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("FinishTime")]
        public string FinishTime
        {
            get { return _FinishTime; }
            set
            {
                this.OnPropertyValueChange("FinishTime");
                this._FinishTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Status")]
        public string Status
        {
            get { return _Status; }
            set
            {
                this.OnPropertyValueChange("Status");
                this._Status = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Error")]
        public string Error
        {
            get { return _Error; }
            set
            {
                this.OnPropertyValueChange("Error");
                this._Error = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("CT")]
        public decimal? CT
        {
            get { return _CT; }
            set
            {
                this.OnPropertyValueChange("CT");
                this._CT = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Barcode")]
        public string Barcode
        {
            get { return _Barcode; }
            set
            {
                this.OnPropertyValueChange("Barcode");
                this._Barcode = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ProductType")]
        public string ProductType
        {
            get { return _ProductType; }
            set
            {
                this.OnPropertyValueChange("ProductType");
                this._ProductType = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Description")]
        public string Description
        {
            get { return _Description; }
            set
            {
                this.OnPropertyValueChange("Description");
                this._Description = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Spcs")]
        public string Spcs
        {
            get { return _Spcs; }
            set
            {
                this.OnPropertyValueChange("Spcs");
                this._Spcs = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Tests")]
        public string Tests
        {
            get { return _Tests; }
            set
            {
                this.OnPropertyValueChange("Tests");
                this._Tests = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Raws")]
        public string Raws
        {
            get { return _Raws; }
            set
            {
                this.OnPropertyValueChange("Raws");
                this._Raws = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("MachineID")]
        public string MachineID
        {
            get { return _MachineID; }
            set
            {
                this.OnPropertyValueChange("MachineID");
                this._MachineID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ProductID")]
        public string ProductID
        {
            get { return _ProductID; }
            set
            {
                this.OnPropertyValueChange("ProductID");
                this._ProductID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("PartID")]
        public string PartID
        {
            get { return _PartID; }
            set
            {
                this.OnPropertyValueChange("PartID");
                this._PartID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("OpID")]
        public string OpID
        {
            get { return _OpID; }
            set
            {
                this.OnPropertyValueChange("OpID");
                this._OpID = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.StartTime,
                _.Barcode,
            };
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.StartTime,
                _.FinishTime,
                _.Status,
                _.Error,
                _.CT,
                _.Barcode,
                _.ProductType,
                _.Description,
                _.Spcs,
                _.Tests,
                _.Raws,
                _.MachineID,
                _.ProductID,
                _.PartID,
                _.OpID,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._StartTime,
                this._FinishTime,
                this._Status,
                this._Error,
                this._CT,
                this._Barcode,
                this._ProductType,
                this._Description,
                this._Spcs,
                this._Tests,
                this._Raws,
                this._MachineID,
                this._ProductID,
                this._PartID,
                this._OpID,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "ProductData");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field StartTime = new Field("StartTime", "ProductData", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field FinishTime = new Field("FinishTime", "ProductData", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Status = new Field("Status", "ProductData", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Error = new Field("Error", "ProductData", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CT = new Field("CT", "ProductData", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Barcode = new Field("Barcode", "ProductData", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ProductType = new Field("ProductType", "ProductData", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Description = new Field("Description", "ProductData", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Spcs = new Field("Spcs", "ProductData", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Tests = new Field("Tests", "ProductData", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Raws = new Field("Raws", "ProductData", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field MachineID = new Field("MachineID", "ProductData", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ProductID = new Field("ProductID", "ProductData", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field PartID = new Field("PartID", "ProductData", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field OpID = new Field("OpID", "ProductData", "");
        }
        #endregion
    }
}