//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Lead.Detect.DatabaseHelper
{
    /// <summary>
    /// 实体类ProductTestDataEntity。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("ProductTestData")]
    [Serializable]
    public partial class ProductTestDataEntity : Entity
    {
        #region Model
		private string _StartTime;
		private string _FinishTime;
		private string _Status;
		private string _Error;
		private decimal? _CT;
		private string _Barcode;
		private string _ProductType;
		private string _Description;
		private string _FAI;
		private string _RAWUP;
		private string _RAWDOWN;

		/// <summary>
		/// 
		/// </summary>
		[Field("StartTime")]
		public string StartTime
		{
			get{ return _StartTime; }
			set
			{
				this.OnPropertyValueChange("StartTime");
				this._StartTime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("FinishTime")]
		public string FinishTime
		{
			get{ return _FinishTime; }
			set
			{
				this.OnPropertyValueChange("FinishTime");
				this._FinishTime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Status")]
		public string Status
		{
			get{ return _Status; }
			set
			{
				this.OnPropertyValueChange("Status");
				this._Status = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Error")]
		public string Error
		{
			get{ return _Error; }
			set
			{
				this.OnPropertyValueChange("Error");
				this._Error = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CT")]
		public decimal? CT
		{
			get{ return _CT; }
			set
			{
				this.OnPropertyValueChange("CT");
				this._CT = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Barcode")]
		public string Barcode
		{
			get{ return _Barcode; }
			set
			{
				this.OnPropertyValueChange("Barcode");
				this._Barcode = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ProductType")]
		public string ProductType
		{
			get{ return _ProductType; }
			set
			{
				this.OnPropertyValueChange("ProductType");
				this._ProductType = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Description")]
		public string Description
		{
			get{ return _Description; }
			set
			{
				this.OnPropertyValueChange("Description");
				this._Description = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("FAI")]
		public string FAI
		{
			get{ return _FAI; }
			set
			{
				this.OnPropertyValueChange("FAI");
				this._FAI = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("RAWUP")]
		public string RAWUP
		{
			get{ return _RAWUP; }
			set
			{
				this.OnPropertyValueChange("RAWUP");
				this._RAWUP = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("RAWDOWN")]
		public string RAWDOWN
		{
			get{ return _RAWDOWN; }
			set
			{
				this.OnPropertyValueChange("RAWDOWN");
				this._RAWDOWN = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.StartTime,
				_.FinishTime,
				_.Status,
				_.Error,
				_.CT,
				_.Barcode,
				_.ProductType,
				_.Description,
				_.FAI,
				_.RAWUP,
				_.RAWDOWN,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._StartTime,
				this._FinishTime,
				this._Status,
				this._Error,
				this._CT,
				this._Barcode,
				this._ProductType,
				this._Description,
				this._FAI,
				this._RAWUP,
				this._RAWDOWN,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "ProductTestData");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field StartTime = new Field("StartTime", "ProductTestData", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field FinishTime = new Field("FinishTime", "ProductTestData", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Status = new Field("Status", "ProductTestData", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Error = new Field("Error", "ProductTestData", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CT = new Field("CT", "ProductTestData", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Barcode = new Field("Barcode", "ProductTestData", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ProductType = new Field("ProductType", "ProductTestData", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Description = new Field("Description", "ProductTestData", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field FAI = new Field("FAI", "ProductTestData", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field RAWUP = new Field("RAWUP", "ProductTestData", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field RAWDOWN = new Field("RAWDOWN", "ProductTestData", "");
        }
        #endregion
	}
}